services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: job-watch-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: job-watch-frontend
    ports:
      - "3000:80"
