services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: jobwatch-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: jobwatch-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
