name: Auto Versioning

on:
  workflow_dispatch:
    inputs:
      update_type:
        description: "Type of version bump: major, minor, patch"
        required: true
        default: patch
  push:
    branches:
      - dev

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: dev

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Bump version
        id: bump_version
        run: |
          cd frontend
          TYPE=${{ github.event.inputs.update_type }}
          if [ -z "$TYPE" ]; then TYPE="patch"; fi
          echo "Update type: $TYPE"

          NEW_VERSION=$(npm version $TYPE --no-git-tag-version)
          NEW_VERSION=${NEW_VERSION//v/}
          echo "Bumped version to $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update version badge in README
        run: |
          VERSION=${{ steps.bump_version.outputs.new_version }}
          echo "Updating README badge to version $VERSION"
          sed -i -E "s|(version-)[0-9]+\.[0-9]+\.[0-9]+(-blue)|\1${VERSION}\2|" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[version bot]"
          git config user.email "github-actions[version bot]@users.noreply.github.com"
          git add frontend/package.json frontend/package-lock.json README.md
          git commit -m "chore: bump version to ${{ steps.bump_version.outputs.new_version }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:dev

      - name: Trigger build-and-push
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.JOBWATCH_REPO_PAT }}
          repository: ethangilles/job-scraper
          event-type: build-and-push
          ref: dev
          client-payload: |
            {
              "branch": "dev",
              "version": "${{ steps.bump_version.outputs.new_version }}"
            }

