name: Build and Push Docker Images

on:
  repository_dispatch:
    types: [build-and-push, prod-build-and-push]

env:
  REGISTRY: ghcr.io
  OWNER: ethangilles
  BACKEND_IMAGE: job-watch-backend
  FRONTEND_IMAGE: job-watch-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract version and branch
        id: meta
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          BRANCH="${{ github.event.client_payload.branch }}"

          if [ -z "$VERSION" ]; then
            echo "Error: version not provided in payload" && exit 1
          fi
          if [ -z "$BRANCH" ]; then
            echo "Warning: branch not provided, defaulting to dev"
            BRANCH="dev"
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "Received build for branch=$BRANCH, version=$VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ethangilles
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.BACKEND_IMAGE }}:v${{ steps.meta.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.BACKEND_IMAGE }}:${{ steps.meta.outputs.branch }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.FRONTEND_IMAGE }}:v${{ steps.meta.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.FRONTEND_IMAGE }}:${{ steps.meta.outputs.branch }}

      - name: Trigger update in flux repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.FLUX_REPO_PAT }}
          repository: ethangilles/kube-homelab
          event-type: update-jobwatch-deploy
          client-payload: |
            {
              "branch": "${{ steps.meta.outputs.branch }}",
              "version": "v${{ steps.meta.outputs.version }}"
            }
