name: Build and Push Docker Images

on:
  push:
    branches:
      - dev
      - main

env:
  REGISTRY: ghcr.io
  OWNER: ethangilles
  BACKEND_IMAGE: job-watch-backend
  FRONTEND_IMAGE: job-watch-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ethangilles
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.BACKEND_IMAGE }}:${{ github.ref_name }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.FRONTEND_IMAGE }}:${{ github.ref_name }}

      - name: Trigger update in flux repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.FLUX_REPO_PAT }}
          repository: ethangilles/kube-homelab
          event-type: update-jobwatch-deploy
          client-payload: |
            {
              "branch": "${{ github.ref_name }}"
            }
